version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock_data_image
    container_name: stock-visualizer-container
    ports:
      - "5003:5000"
    volumes:
      - .:/project
    environment:
      FLASK_ENV: development
